[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py311"

lint.select = [
  "B",  # flake8 bugbear
  "C4",  # flake8 comprehensions
  "C9",  # flake8 McCabe
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "UP",  # pyupgrade
]
lint.ignore = ["E501"]
